name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-version: [3.7,3.8,3.9]
        os: ["ubuntu-latest","macos-latest","windows-latest"]
    steps:
    - name: Set up Python
      uses: ${{ matrix.os }}
      with:
        python-version: ${{ matrix.py-version }}
        
