name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-version: [3.7,3.8,3.9]
        os: ["ubuntu-latest","macos-latest","windows-latest"]
        exclude:
        - os: macos-latest
          py-version: 3.9
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.py-version }}
        
